FROM node:14.0.0-alpine

WORKDIR /usr/src/app

COPY  package*.json ./

RUN yarn config set ignore-engines true

RUN npm install

COPY . .

RUN npm run build

RUN npm install -g serve

#EXPOSE 3000

#CMD ["node", "run start"]